### ISSUE TITLE
Plugin installation not working

### ISSUE THREAD

**Issue by jczmok-iag** [netboxlabs/diode-netbox-plugin#100]
### Diode NetBox Plugin version

1.0.0

### NetBox version

NetBox Community v4.2.8 (2025-04-22)

### Diode version

latest git

### Diode SDK type

diode-sdk-python

### Diode SDK version

v1.0.0

### Steps to reproduce

1. Server installation (https://github.com/netboxlabs/diode/tree/develop/diode-server#readme)
2. Plugin install (which fails): https://github.com/netboxlabs/diode-netbox-plugin

According to docs, migrate:

(venv) root@netbox:/opt/netbox# cd /opt/netbox/netbox
./manage.py migrate netbox_diode_plugin
Operations to perform:
  Apply all migrations: netbox_diode_plugin
Running migrations:
  No migrations to apply.
  Your models in app(s): 'netbox_diode_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

Also makemigrations does not work
CommandError: This command is available for development purposes only. It will
NOT resolve any issues with missing or unapplied migrations. For assistance,
please post to the NetBox discussion forum on GitHub:
    https://github.com/netbox-community/netbox/discussions

Then try to run the usual stuff:

python3 /opt/netbox/netbox/manage.py migrate
python3 /opt/netbox/netbox/manage.py collectstatic

venv) root@netbox:/opt/netbox/netbox# python3 /opt/netbox/netbox/manage.py migrate
Operations to perform:
  Apply all migrations: account, auth, circuits, contenttypes, core, dcim, django_rq, extras, ipam, netbox_acls, netbox_bgp, netbox_config_diff, netbox_diode_plugin, netbox_floorplan, netbox_inventory, netbox_secrets, netbox_topology_views, sessions, social_django, taggit, tenancy, users, validity, virtualization, vpn, wireless
Running migrations:
  No migrations to apply.
  Your models in app(s): 'netbox_diode_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
CommandError: This command is available for development purposes only. It will
NOT resolve any issues with missing or unapplied migrations. For assistance,
please post to the NetBox discussion forum on GitHub:
    https://github.com/netbox-community/netbox/discussions

Please advise

### Expected behavior

working :-)

### Observed behavior

see above.

**Comment by sandyis** [comment]
I also cannot install the diode plugging but getting different error @mfiedorowicz , last week because 1.0.0 was not published but today looks like  _netbox-plugin.yaml_ file 


- python is 3.10
- netbox 4.2.8 new clean install
- tried to install diode-netbox-plugin as per [this guide](https://github.com/netboxlabs/diode-netbox-plugin#installation)
- is it possible that it is because in the netbox-plugin.yaml max version is 4.2.3 ?
- `version: 0.1
package_name: netboxlabs-diode-netbox-plugin
compatibility:
  - release: 1.0.0
    netbox_min: 4.2.3
    netbox_max: 4.2.3`

`sudo pip install netboxlabs-diode-netbox-plugin=1.0.0
ERROR: Invalid requirement: 'netboxlabs-diode-netbox-plugin=1.0.0'
Hint: = is not a valid operator. Did you mean == ?
hnsi@hnsiai2:/opt/netbox$ sudo pip install netboxlabs-diode-netbox-plugin==1.0.0
Collecting netboxlabs-diode-netbox-plugin==1.0.0
  Using cached netboxlabs_diode_netbox_plugin-1.0.0.tar.gz (40 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package netboxlabs-diode-netbox-plugin produced metadata for project name unknown. Fix your #egg=netboxlabs-diode-netbox-plugin fragments.
Discarding https://files.pythonhosted.org/packages/3b/7e/070fdaeb26ae776ea36d11afc9fc050bc1b4739418e20e0cec0af1663185/netboxlabs_diode_netbox_plugin-1.0.0.tar.gz#sha256=3bd91bf3e8cd5a2696c8570f9af25d670dffebe3ae312b74ff065a17fbb20fa3 (from https://pypi.org/simple/netboxlabs-diode-netbox-plugin/) (requires-python:>=3.8): Requested unknown from https://files.pythonhosted.org/packages/3b/7e/070fdaeb26ae776ea36d11afc9fc050bc1b4739418e20e0cec0af1663185/netboxlabs_diode_netbox_plugin-1.0.0.tar.gz#sha256=3bd91bf3e8cd5a2696c8570f9af25d670dffebe3ae312b74ff065a17fbb20fa3 has inconsistent name: filename has 'netboxlabs-diode-netbox-plugin', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement netboxlabs-diode-netbox-plugin==1.0.0 (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 1.0.0)
ERROR: No matching distribution found for netboxlabs-diode-netbox-plugin==1.0.0
`

**Comment by mfiedorowicz** [comment]
> I also cannot install the diode plugging but getting different error [@mfiedorowicz](https://github.com/mfiedorowicz) , last week because 1.0.0 was not published but today looks like _netbox-plugin.yaml_ file
> 
> * python is 3.10
> * netbox 4.2.8 new clean install
> * tried to install diode-netbox-plugin as per [this guide](https://github.com/netboxlabs/diode-netbox-plugin#installation)
> * is it possible that it is because in the netbox-plugin.yaml max version is 4.2.3 ?
> * `version: 0.1
>   package_name: netboxlabs-diode-netbox-plugin
>   compatibility:
>   
>   * release: 1.0.0
>     netbox_min: 4.2.3
>     netbox_max: 4.2.3`
> 
> `sudo pip install netboxlabs-diode-netbox-plugin=1.0.0 ERROR: Invalid requirement: 'netboxlabs-diode-netbox-plugin=1.0.0' Hint: = is not a valid operator. Did you mean == ? hnsi@hnsiai2:/opt/netbox$ sudo pip install netboxlabs-diode-netbox-plugin==1.0.0 Collecting netboxlabs-diode-netbox-plugin==1.0.0 Using cached netboxlabs_diode_netbox_plugin-1.0.0.tar.gz (40 kB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... done WARNING: Generating metadata for package netboxlabs-diode-netbox-plugin produced metadata for project name unknown. Fix your #egg=netboxlabs-diode-netbox-plugin fragments. Discarding https://files.pythonhosted.org/packages/3b/7e/070fdaeb26ae776ea36d11afc9fc050bc1b4739418e20e0cec0af1663185/netboxlabs_diode_netbox_plugin-1.0.0.tar.gz#sha256=3bd91bf3e8cd5a2696c8570f9af25d670dffebe3ae312b74ff065a17fbb20fa3 (from https://pypi.org/simple/netboxlabs-diode-netbox-plugin/) (requires-python:>=3.8): Requested unknown from https://files.pythonhosted.org/packages/3b/7e/070fdaeb26ae776ea36d11afc9fc050bc1b4739418e20e0cec0af1663185/netboxlabs_diode_netbox_plugin-1.0.0.tar.gz#sha256=3bd91bf3e8cd5a2696c8570f9af25d670dffebe3ae312b74ff065a17fbb20fa3 has inconsistent name: filename has 'netboxlabs-diode-netbox-plugin', but metadata has 'unknown' ERROR: Could not find a version that satisfies the requirement netboxlabs-diode-netbox-plugin==1.0.0 (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 1.0.0) ERROR: No matching distribution found for netboxlabs-diode-netbox-plugin==1.0.0 `

`netbox-plugin.yaml` doesn't affect installation with pip. In your error output it explicitly says to try `pip install netboxlabs-diode-netbox-plugin==1.0.0`

**Comment by mfiedorowicz** [comment]
Re: plugin installation issue, did you have previous version(s) of the `netbox_diode_plugin` installed on this NetBox instance? What does `./manage.py showmigrations netbox_diode_plugin` say?

**Comment by sandyis** [comment]
> Re: plugin installation issue, did you have previous version(s) of the `netbox_diode_plugin` installed on this NetBox instance? What does `./manage.py showmigrations netbox_diode_plugin` say?

no it is a clean install of netbox in a python virtual env @mfiedorowicz 

` ./manage.py showmigrations netbox_diode_plugin
No installed app with label 'netbox_diode_plugin'.
`
this command didinot work and then i realized need to be `netbox` executable folder which in my case is some how one level down `/opt/netbox/netbox`
 

should below change in readme/install steps to `cd /opt/netbox/netbox`

```
Source the NetBox Python virtual environment:

cd /opt/netbox
source venv/bin/activate
```

**Comment by tobiasstein** [comment]
I guess I've got the same issue and I'll try to provide the requested information.
I started the installation with netbox v4.1.1, but when I remember correctly, netboxlabs-diode-netbox-plugin required v4.2.4, so I upgraded to netbox latest which was v4.3.0.

```
root@netbox:~#
root@netbox:~# cd /opt/netbox
root@netbox:/opt/netbox# source venv/bin/activate
(venv) root@netbox:/opt/netbox# cd netbox/
(venv) root@netbox:/opt/netbox/netbox# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
(venv) root@netbox:/opt/netbox/netbox# git branch
* (HEAD detached at v4.3.0)
  master

(venv) root@netbox:/opt/netbox/netbox# ./manage.py showmigrations netbox_diode_plugin
netbox_diode_plugin
 [X] 0001_squashed_0005 (5 squashed migrations)

(venv) root@netbox:/opt/netbox/netbox# pip install netboxlabs-diode-netbox-plugin
Requirement already satisfied: netboxlabs-diode-netbox-plugin in /opt/netbox/venv/lib/python3.11/site-packages (1.0.0)
Requirement already satisfied: Brotli>=1.1.0 in /opt/netbox/venv/lib/python3.11/site-packages (from netboxlabs-diode-netbox-plugin) (1.1.0)
Requirement already satisfied: certifi>=2024.7.4 in /opt/netbox/venv/lib/python3.11/site-packages (from netboxlabs-diode-netbox-plugin) (2025.4.26)
Requirement already satisfied: grpcio>=1.68.1 in /opt/netbox/venv/lib/python3.11/site-packages (from netboxlabs-diode-netbox-plugin) (1.71.0)
Requirement already satisfied: protobuf>=5.28.1 in /opt/netbox/venv/lib/python3.11/site-packages (from netboxlabs-diode-netbox-plugin) (5.29.4)

(venv) root@netbox:/opt/netbox/netbox# pip list --outdated
Package                        Version Latest  Type
------------------------------ ------- ------- -----
click                          8.1.8   8.2.0   wheel
Django                         5.2     5.2.1   wheel
django-rich                    1.14.0  2.0.0   wheel
mkdocs-material                9.6.12  9.6.14  wheel
netboxlabs-diode-netbox-plugin 1.0.0   1.0.1   sdist
protobuf                       5.29.4  6.31.0  wheel
psycopg                        3.2.7   3.2.9   wheel
psycopg-c                      3.2.7   3.2.9   sdist
pyyaml_env_tag                 0.1     1.1     wheel
redis                          6.0.0   6.1.0   wheel
rq                             2.3.2   2.3.3   wheel
sentry-sdk                     2.27.0  2.28.0  wheel
setuptools                     66.1.1  80.4.0  wheel
strawberry-graphql             0.266.0 0.268.1 wheel
strawberry-graphql-django      0.58.0  0.59.1  wheel

(venv) root@netbox:/opt/netbox/netbox# pip install -U netboxlabs-diode-netbox-plugin
Requirement already satisfied: netboxlabs-diode-netbox-plugin in /opt/netbox/venv/lib/python3.11/site-packages (1.0.0)
Collecting netboxlabs-diode-netbox-plugin
  Downloading netboxlabs_diode_netbox_plugin-1.0.1.tar.gz (40 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: Brotli>=1.1.0 in /opt/netbox/venv/lib/python3.11/site-packages (from netboxlabs-diode-netbox-plugin) (1.1.0)
Requirement already satisfied: certifi>=2024.7.4 in /opt/netbox/venv/lib/python3.11/site-packages (from netboxlabs-diode-netbox-plugin) (2025.4.26)
Requirement already satisfied: grpcio>=1.68.1 in /opt/netbox/venv/lib/python3.11/site-packages (from netboxlabs-diode-netbox-plugin) (1.71.0)
Requirement already satisfied: protobuf>=5.28.1 in /opt/netbox/venv/lib/python3.11/site-packages (from netboxlabs-diode-netbox-plugin) (5.29.4)
Building wheels for collected packages: netboxlabs-diode-netbox-plugin
  Building wheel for netboxlabs-diode-netbox-plugin (pyproject.toml) ... done
  Created wheel for netboxlabs-diode-netbox-plugin: filename=netboxlabs_diode_netbox_plugin-1.0.1-py3-none-any.whl size=47834 sha256=77f7bc85386f81417881f5a6f1575acff605965fb2f86794ca7fc16e0be71f5
8
  Stored in directory: /root/.cache/pip/wheels/4a/23/ca/94f92187900c2a49607f6e2e3e03f4e3f468ab6aafc24b9e9c
Successfully built netboxlabs-diode-netbox-plugin 
Installing collected packages: netboxlabs-diode-netbox-plugin
  Attempting uninstall: netboxlabs-diode-netbox-plugin
    Found existing installation: netboxlabs-diode-netbox-plugin 1.0.0
    Uninstalling netboxlabs-diode-netbox-plugin-1.0.0:
      Successfully uninstalled netboxlabs-diode-netbox-plugin-1.0.0
Successfully installed netboxlabs-diode-netbox-plugin-1.0.1

(venv) root@netbox:/opt/netbox/netbox# ./manage.py migrate                                         
Operations to perform:
  Apply all migrations: account, auth, circuits, contenttypes, core, dcim, django_rq, extras, ipam, netbox_diode_plugin, sessions, social_django, taggit, tenancy, users, virtualization, vpn, wirel
ess
Running migrations:
  No migrations to apply.
  Your models in app(s): 'netbox_diode_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
(venv) root@netbox:/opt/netbox/netbox# ./manage.py makemigrations                                  
CommandError: This command is available for development purposes only. It will
NOT resolve any issues with missing or unapplied migrations. For assistance,
please post to the NetBox discussion forum on GitHub:
    https://github.com/netbox-community/netbox/discussions

(venv) root@netbox:/opt/netbox/netbox# ./manage.py migrate
Operations to perform:
  Apply all migrations: account, auth, circuits, contenttypes, core, dcim, django_rq, extras, ipam, netbox_diode_plugin, sessions, social_django, taggit, tenancy, users, virtualization, vpn, wirel
ess
Running migrations:
  No migrations to apply.
  Your models in app(s): 'netbox_diode_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

(venv) root@netbox:/opt/netbox/netbox# ./manage.py showmigrations netbox_diode_plugin
netbox_diode_plugin
 [X] 0001_squashed_0005 (5 squashed migrations)
```

**Comment by wessrow** [comment]
Also having the same issue.
This is on the recommended Netbox-version 4.2.3, fresh install with no previous netbox-diode-installation. Tested with both plugin version 1.0.0 which is the tested version, as well as with 1.0.1 that was released a few days ago:

```bash
(venv) unit@47c6a932d623:/opt/netbox/netbox$ cd /opt/netbox/netbox && ./manage.py migrate netbox_diode_plugin

🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
Operations to perform:
  Apply all migrations: netbox_diode_plugin
Running migrations:
  No migrations to apply.
  Your models in app(s): 'netbox_diode_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
(venv) unit@47c6a932d623:/opt/netbox/netbox$
(venv) unit@47c6a932d623:/opt/netbox/netbox$ cd /opt/netbox/netbox && ./manage.py makemigrations
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
CommandError: This command is available for development purposes only. It will
NOT resolve any issues with missing or unapplied migrations. For assistance,
please post to the NetBox discussion forum on GitHub:
    https://github.com/netbox-community/netbox/discussions
(venv) unit@47c6a932d623:/opt/netbox/netbox$ cd /opt/netbox/netbox && ./manage.py showmigrations netbox_diode_plugin
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
netbox_diode_plugin
 [X] 0001_squashed_0005 (5 squashed migrations)
```

**Comment by mfiedorowicz** [comment]
Thanks for all reports, we will investigate it soon and keep you updated

**Comment by wessrow** [comment]
I also did some further testing on this to see if there were previous requirements through the upgrade path missing:

Starting from NB 4.1.0, installing plugin v0.4.0 and working myself up through:

NB: 4.1.0, Plugin: 0.4.0 - Migrations OK
NB: 4.2.3, Plugin: 0.5.0 - Migrations OK
NB: 4.2.3, Plugin: 0.6.0 - Migrations OK
NB: 4.2.3, Plugin: 1.0.0 - No migrations found, and the settings under the Plugin view disappears.

Even when upgrading and keeping the settings throughout, it ends up in the same place, automatic migration doesn't run - and manual results in:
```bash
unit@f9f9b41424e5:/opt/netbox/netbox$ source ../venv/bin/activate
(venv) unit@f9f9b41424e5:/opt/netbox/netbox$ cd /opt/netbox/netbox && ./manage.py migrate netbox_diode_plugin
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
Operations to perform:
  Apply all migrations: netbox_diode_plugin
Running migrations:
  No migrations to apply.
  Your models in app(s): 'netbox_diode_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
(venv) unit@f9f9b41424e5:/opt/netbox/netbox$
```

So something in the migration-script for 0.6.0 to 1.0.0 doesn't seem to work as intended.

**Comment by mfiedorowicz** [comment]
1.0.0 have all old migrations squashed into one and replace them, hence nothing to apply (update: when migrating from 0.6.0)

**Comment by LeighBennettCP** [comment]
I have the same issue today. I came across this trying to troubleshoot why I do not have a 'Ingestion Logs' option within the Netbox GUI. I seem to have everything else working now such as Netbox/Diode/Orb-agent.

![Image](https://github.com/user-attachments/assets/395bef9b-e85a-49e6-a9f7-09ef468ed607)

All I see is:
Diode > Settings
Diode > Client Credentials

I was retracing my steps of the plugin installation and encountered this.

```
(venv) [root@host netbox]# cd /opt/netbox/netbox
./manage.py migrate netbox_diode_plugin
Operations to perform:
  Apply all migrations: netbox_diode_plugin
Running migrations:
  No migrations to apply.
  Your models in app(s): 'netbox_diode_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
(venv) [root@host netbox]#

```

could this be the reason why the Diode > Ingestion Logs option seems to be missing?

Netbox version 4.2.4

![Image](https://github.com/user-attachments/assets/26c39df0-174b-4495-8a63-125adf23704a)

**Comment by joeladria** [comment]
@LeighBennettCP the Ingestion Logs function seems to have been removed. I can only speculate that maybe this will be packaged as part of the Server component or maybe as part of NetBox Assurance? But somewhat difficult to understand what's going on with the service without it!
https://github.com/netboxlabs/diode-netbox-plugin/compare/v0.6.0...v1.1.0

**Comment by mfiedorowicz** [comment]
Ingestion logs have been removed in diode-netbox-plugin 1.0.0, this plugin's main purposes are API and settings + client credentials. Ingested / reconciled data viewer will be added a little bit later.

**Comment by toystorykiwi** [comment]
i'm facing the exact the same problem with NetBox Community v4.2.5-Docker-3.2.0 and Diode Plugin 1.3
When i run the command 
`docker compose exec netbox python3 manage.py migrate`

i got the the same output

`🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
Operations to perform:
  Apply all migrations: account, auth, circuits, contenttypes, core, dcim, django_rq, extras, ipam, netbox_bgp, netbox_diode_plugin, netbox_topology_views, sessions, social_django, taggit, tenancy, users, virtualization, vpn, wireless
Running migrations:
  No migrations to apply.
  Your models in app(s): 'netbox_diode_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.`

Do you have any update or suggetion how i could fix it?

**Comment by mfiedorowicz** [comment]
@toystorykiwi have you tried to use netbox with diode plugin regardless of this migrate command output? it should work regardless

**Comment by toystorykiwi** [comment]
Not yet I was trying to be sure that all task for plugin installation works fine

edit: confirm that diode and orb agent are working even this error during the migration
I will perform more test to undestand if this behavior can lead other problem during the setup of additional plugin

**Comment by e1z0** [comment]
Having the same issue, netbox-v4.4.1 community, the plugin itself seems to be working, but when viewing netbox > admin > system, it throws this error:

<img width="946" height="670" alt="Image" src="https://github.com/user-attachments/assets/29b79711-eb97-4b11-b2a9-0177aa4800d9" />

* PostgreSQL v17.4
* All migrations are applied already..

**Comment by mfiedorowicz** [comment]
> Having the same issue, netbox-v4.4.1 community, the plugin itself seems to be working, but when viewing netbox > admin > system, it throws this error:
> 
> <img alt="Image" width="946" height="670" src="https://private-user-images.githubusercontent.com/7213361/491456887-29b79711-eb97-4b11-b2a9-0177aa4800d9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgyNjkxMjMsIm5iZiI6MTc1ODI2ODgyMywicGF0aCI6Ii83MjEzMzYxLzQ5MTQ1Njg4Ny0yOWI3OTcxMS1lYjk3LTRiMTEtYjJhOS0wMTc3YWE0ODAwZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MTlUMDgwMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Q2NGQ2MmY1M2FkOWVhNWMxYWM0NmZhZGNhNjA5YjViOGIzZmYzYzUzMjMzNWQ5M2I2NDBkZjVjN2M2ZmFiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.EIFS7pJYw2YnIZ9wAQOwBjjSsoXRkSM1B5jGGv7iYXg">
> * PostgreSQL v17.4
> * All migrations are applied already..

That's odd, thanks for reporting, will attempt to reproduce it.

**Comment by colthouse** [comment]
I have the same issue. I followed [this guide](https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins) from the netbox-docker project in addition to the instructions provided on the instance itself under admin > plugins > Netbox Diode > Install.

I just found [this guide](https://github.com/netboxlabs/diode-netbox-plugin/blob/develop/README.md) which is different from the instructions on my instance. This might fix the issue, I'll report back

Edit0:
It did not help. I still have the same issue. A couple of things that might be interesting:
The squashed migration was applied: 
```text
  Applying ipam.0078_iprange_mark_utilized... OK
  Applying ipam.0079_add_service_fhrp_group_parent_gfk... OK
  Applying ipam.0080_populate_service_parent... OK
  Applying ipam.0081_remove_service_device_virtual_machine_add_parent_gfk_index... OK
  Applying ipam.0082_add_prefix_network_containment_indexes... OK
  Applying netbox_diode_plugin.0001_squashed_0005... OK
  Applying sessions.0001_initial... OK
  Applying social_django.0001_initial... OK
  Applying social_django.0002_add_related_name... OK
  Applying social_django.0003_alter_email_max_length... OK
  Applying social_django.0004_auto_20160423_0400... OK
```

When I try to fix the issue by running `manage.py makemigrations` it throws a permission denied error for a file that doesn't exist.
```text
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
Migrations for 'netbox_diode_plugin':
  /opt/netbox/venv/lib/python3.12/site-packages/netbox_diode_plugin/migrations/0006_clientcredentials_alter_setting_diode_target.py
    + Create model ClientCredentials
    ~ Alter field diode_target on setting
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 416, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/core/management/commands/makemigrations.py", line 22, in handle
    super().handle(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/commands/makemigrations.py", line 260, in handle
    self.write_migration_files(changes)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/commands/makemigrations.py", line 366, in write_migration_files
    with open(writer.path, "w", encoding="utf-8") as fh:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/netbox/venv/lib/python3.12/site-packages/netbox_diode_plugin/migrations/0006_clientcredentials_alter_setting_diode_target.py'
```

Edit1:
Fixed the permission issue, possibly related to https://github.com/netbox-community/netbox-docker/issues/1488. Then used `manage.py makemigrations` and `manage.py migrate`. Didn't fix anything ):

Edit2:
My plugin version is 1.3.1 and my instance is NetBox Community v4.4.1-Docker-3.4.0. Based the plugin page the maximum Netbox version is 4.3.7 could that be the problem? 

Edit3:
Yep, downgrading to 4.3.7 worked like a charm. The error is now gone

**Comment by sml12179** [comment]
@colthouse After downgrading are you able to fully use diode? I have downgraded and it looks like netbox is not reaching out Diode itself now. Getting "Failed to obtain access token: Not Found" logs on diode-server docker instance do not show netbox hitting it.

**Comment by colthouse** [comment]
@sml12179 Yes, it worked. I think your issue is related to the plugin configuration. Specifically the "Not Found" part sounds like it reaches the wrong web-server. 
Also I didn't have to touch the access token section in the Netbox web-ui. I don't know what I could use that section for but it wasn't needed to setup Diode with Orb.

This is what my `configuration/plugins.py` looks like. Make sure `netbox_to_diode_client_secret` is set correctly (according to `oauth2/client/something` file from diode). With `diode_target_override` be careful with the port. In my case Diode (Nginx) is running on port 8000 **not 8080**

```python
# Add your plugins and plugin settings here.
# Of course uncomment this file out.

# To learn how to build images with your required plugins
# See https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins

PLUGINS = ["netbox_diode_plugin"]

PLUGINS_CONFIG = {
    "netbox_diode_plugin": {
        # Diode gRPC target for communication with Diode server
        "diode_target_override": "grpc://localhost:8000/diode",

        # Username associated with changes applied via plugin
        "diode_username": "diode",

        # netbox-to-diode client_secret created during diode bootstrap.
        "netbox_to_diode_client_secret": "<hidden>"
    },
}
```
Edit0:
Also make sure to set those env variable correctly in the .env file for Diode: `NETBOX_DIODE_PLUGIN_API_BASE_URL` should be something like `https://netbox.example.com/api/plugins/diode` and `NETBOX_DIODE_PLUGIN_SKIP_TLS_VERIFY` to `false` when using a self signed certificate

**Comment by mfiedorowicz** [comment]
Putting `python3 manage.py migrate` warning aside (plugin should work regardless), is it working now?

**Comment by sml12179** [comment]
@colthouse I was able to resolve the issue by running diode on a separate server. I was trying to test both locally.

@mfiedorowicz I have it working as well with v4.3.7. I did just test with v4.4.0-3.4.0 and v4.4.2-3.4.1 with diode plugin 1.4.0, still having the original issue.

**Comment by mfiedorowicz** [comment]
> [@colthouse](https://github.com/colthouse) I was able to resolve the issue by running diode on a separate server. I was trying to test both locally.
> 
> [@mfiedorowicz](https://github.com/mfiedorowicz) I have it working as well with v4.3.7. I did just test with v4.4.0-3.4.0 and v4.4.2-3.4.1 with diode plugin 1.4.0, still having the original issue.

Might be configuration between diode and netbox with plugin a long the way, there should be no issue like that when switching from NB 4.3.x to 4.4.x

**Comment by mfiedorowicz** [comment]
The warning about migrations `Your models in app(s): 'netbox_diode_plugin' have changes that are not yet reflected in a migration...` should be resolved in next release

**Comment by sml12179** [comment]
@mfiedorowicz I originally had the same problem as this issues original statement. I was able to resolve the original issue by downgrading to netbox-docker v4.3.7-3.3.0. After resolving that issue I was presented with a new issue of "Failed to obtain access token: Not Found". That issue was resolved by running netbox-docker and diode on seperate hardware. Then when trying out v4.4.x-3.4.x with diode-plugin 1.4.0 I was presented with the original issue again. Also see the just raised issue #136, I believe they are one in the same.

**Comment by leoparente** [comment]
hi @sml12179 can you validate v4.4.x with diode-plugin 1.4.1? The issue should be fixed. Also @e1z0.

**Comment by sml12179** [comment]
@leoparente Validated and working.

**Comment by leoparente** [comment]
I’ll close this ticket now, as it seems that all the issues mentioned in this thread have been resolved. If anyone encounters a new issue related to plugin installation, please feel free to open a new ticket or reopen this one.
